// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: generator.proto

package generatorpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	generatorpb "quote_generator/generatorpb"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GeneratorServiceName is the fully-qualified name of the GeneratorService service.
	GeneratorServiceName = "generator.GeneratorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GeneratorServiceGetRandomNumberProcedure is the fully-qualified name of the GeneratorService's
	// GetRandomNumber RPC.
	GeneratorServiceGetRandomNumberProcedure = "/generator.GeneratorService/GetRandomNumber"
	// GeneratorServiceGetRandomQuoteProcedure is the fully-qualified name of the GeneratorService's
	// GetRandomQuote RPC.
	GeneratorServiceGetRandomQuoteProcedure = "/generator.GeneratorService/GetRandomQuote"
)

// GeneratorServiceClient is a client for the generator.GeneratorService service.
type GeneratorServiceClient interface {
	GetRandomNumber(context.Context, *connect.Request[generatorpb.GetRandomNumberRequest]) (*connect.Response[generatorpb.GetRandomNumberResponse], error)
	GetRandomQuote(context.Context, *connect.Request[generatorpb.GetRandomQuoteRequest]) (*connect.Response[generatorpb.GetRandomQuoteResponse], error)
}

// NewGeneratorServiceClient constructs a client for the generator.GeneratorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGeneratorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GeneratorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	generatorServiceMethods := generatorpb.File_generator_proto.Services().ByName("GeneratorService").Methods()
	return &generatorServiceClient{
		getRandomNumber: connect.NewClient[generatorpb.GetRandomNumberRequest, generatorpb.GetRandomNumberResponse](
			httpClient,
			baseURL+GeneratorServiceGetRandomNumberProcedure,
			connect.WithSchema(generatorServiceMethods.ByName("GetRandomNumber")),
			connect.WithClientOptions(opts...),
		),
		getRandomQuote: connect.NewClient[generatorpb.GetRandomQuoteRequest, generatorpb.GetRandomQuoteResponse](
			httpClient,
			baseURL+GeneratorServiceGetRandomQuoteProcedure,
			connect.WithSchema(generatorServiceMethods.ByName("GetRandomQuote")),
			connect.WithClientOptions(opts...),
		),
	}
}

// generatorServiceClient implements GeneratorServiceClient.
type generatorServiceClient struct {
	getRandomNumber *connect.Client[generatorpb.GetRandomNumberRequest, generatorpb.GetRandomNumberResponse]
	getRandomQuote  *connect.Client[generatorpb.GetRandomQuoteRequest, generatorpb.GetRandomQuoteResponse]
}

// GetRandomNumber calls generator.GeneratorService.GetRandomNumber.
func (c *generatorServiceClient) GetRandomNumber(ctx context.Context, req *connect.Request[generatorpb.GetRandomNumberRequest]) (*connect.Response[generatorpb.GetRandomNumberResponse], error) {
	return c.getRandomNumber.CallUnary(ctx, req)
}

// GetRandomQuote calls generator.GeneratorService.GetRandomQuote.
func (c *generatorServiceClient) GetRandomQuote(ctx context.Context, req *connect.Request[generatorpb.GetRandomQuoteRequest]) (*connect.Response[generatorpb.GetRandomQuoteResponse], error) {
	return c.getRandomQuote.CallUnary(ctx, req)
}

// GeneratorServiceHandler is an implementation of the generator.GeneratorService service.
type GeneratorServiceHandler interface {
	GetRandomNumber(context.Context, *connect.Request[generatorpb.GetRandomNumberRequest]) (*connect.Response[generatorpb.GetRandomNumberResponse], error)
	GetRandomQuote(context.Context, *connect.Request[generatorpb.GetRandomQuoteRequest]) (*connect.Response[generatorpb.GetRandomQuoteResponse], error)
}

// NewGeneratorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGeneratorServiceHandler(svc GeneratorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	generatorServiceMethods := generatorpb.File_generator_proto.Services().ByName("GeneratorService").Methods()
	generatorServiceGetRandomNumberHandler := connect.NewUnaryHandler(
		GeneratorServiceGetRandomNumberProcedure,
		svc.GetRandomNumber,
		connect.WithSchema(generatorServiceMethods.ByName("GetRandomNumber")),
		connect.WithHandlerOptions(opts...),
	)
	generatorServiceGetRandomQuoteHandler := connect.NewUnaryHandler(
		GeneratorServiceGetRandomQuoteProcedure,
		svc.GetRandomQuote,
		connect.WithSchema(generatorServiceMethods.ByName("GetRandomQuote")),
		connect.WithHandlerOptions(opts...),
	)
	return "/generator.GeneratorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GeneratorServiceGetRandomNumberProcedure:
			generatorServiceGetRandomNumberHandler.ServeHTTP(w, r)
		case GeneratorServiceGetRandomQuoteProcedure:
			generatorServiceGetRandomQuoteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGeneratorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGeneratorServiceHandler struct{}

func (UnimplementedGeneratorServiceHandler) GetRandomNumber(context.Context, *connect.Request[generatorpb.GetRandomNumberRequest]) (*connect.Response[generatorpb.GetRandomNumberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("generator.GeneratorService.GetRandomNumber is not implemented"))
}

func (UnimplementedGeneratorServiceHandler) GetRandomQuote(context.Context, *connect.Request[generatorpb.GetRandomQuoteRequest]) (*connect.Response[generatorpb.GetRandomQuoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("generator.GeneratorService.GetRandomQuote is not implemented"))
}
