// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: generator.proto

package generatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 随机数请求与响应
type GetRandomNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomNumberRequest) Reset() {
	*x = GetRandomNumberRequest{}
	mi := &file_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomNumberRequest) ProtoMessage() {}

func (x *GetRandomNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomNumberRequest.ProtoReflect.Descriptor instead.
func (*GetRandomNumberRequest) Descriptor() ([]byte, []int) {
	return file_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandomNumberRequest) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *GetRandomNumberRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type GetRandomNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomNumberResponse) Reset() {
	*x = GetRandomNumberResponse{}
	mi := &file_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomNumberResponse) ProtoMessage() {}

func (x *GetRandomNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomNumberResponse.ProtoReflect.Descriptor instead.
func (*GetRandomNumberResponse) Descriptor() ([]byte, []int) {
	return file_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GetRandomNumberResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

// 随机名言请求与响应
type GetRandomQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomQuoteRequest) Reset() {
	*x = GetRandomQuoteRequest{}
	mi := &file_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomQuoteRequest) ProtoMessage() {}

func (x *GetRandomQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetRandomQuoteRequest) Descriptor() ([]byte, []int) {
	return file_generator_proto_rawDescGZIP(), []int{2}
}

type GetRandomQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quote         string                 `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomQuoteResponse) Reset() {
	*x = GetRandomQuoteResponse{}
	mi := &file_generator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomQuoteResponse) ProtoMessage() {}

func (x *GetRandomQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetRandomQuoteResponse) Descriptor() ([]byte, []int) {
	return file_generator_proto_rawDescGZIP(), []int{3}
}

func (x *GetRandomQuoteResponse) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

var File_generator_proto protoreflect.FileDescriptor

const file_generator_proto_rawDesc = "" +
	"\n" +
	"\x0fgenerator.proto\x12\tgenerator\"<\n" +
	"\x16GetRandomNumberRequest\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"1\n" +
	"\x17GetRandomNumberResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\"\x17\n" +
	"\x15GetRandomQuoteRequest\".\n" +
	"\x16GetRandomQuoteResponse\x12\x14\n" +
	"\x05quote\x18\x01 \x01(\tR\x05quote2\xc3\x01\n" +
	"\x10GeneratorService\x12X\n" +
	"\x0fGetRandomNumber\x12!.generator.GetRandomNumberRequest\x1a\".generator.GetRandomNumberResponse\x12U\n" +
	"\x0eGetRandomQuote\x12 .generator.GetRandomQuoteRequest\x1a!.generator.GetRandomQuoteResponseB1Z/quote_generator/backend/generatorpb;generatorpbb\x06proto3"

var (
	file_generator_proto_rawDescOnce sync.Once
	file_generator_proto_rawDescData []byte
)

func file_generator_proto_rawDescGZIP() []byte {
	file_generator_proto_rawDescOnce.Do(func() {
		file_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generator_proto_rawDesc), len(file_generator_proto_rawDesc)))
	})
	return file_generator_proto_rawDescData
}

var file_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_generator_proto_goTypes = []any{
	(*GetRandomNumberRequest)(nil),  // 0: generator.GetRandomNumberRequest
	(*GetRandomNumberResponse)(nil), // 1: generator.GetRandomNumberResponse
	(*GetRandomQuoteRequest)(nil),   // 2: generator.GetRandomQuoteRequest
	(*GetRandomQuoteResponse)(nil),  // 3: generator.GetRandomQuoteResponse
}
var file_generator_proto_depIdxs = []int32{
	0, // 0: generator.GeneratorService.GetRandomNumber:input_type -> generator.GetRandomNumberRequest
	2, // 1: generator.GeneratorService.GetRandomQuote:input_type -> generator.GetRandomQuoteRequest
	1, // 2: generator.GeneratorService.GetRandomNumber:output_type -> generator.GetRandomNumberResponse
	3, // 3: generator.GeneratorService.GetRandomQuote:output_type -> generator.GetRandomQuoteResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_generator_proto_init() }
func file_generator_proto_init() {
	if File_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generator_proto_rawDesc), len(file_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generator_proto_goTypes,
		DependencyIndexes: file_generator_proto_depIdxs,
		MessageInfos:      file_generator_proto_msgTypes,
	}.Build()
	File_generator_proto = out.File
	file_generator_proto_goTypes = nil
	file_generator_proto_depIdxs = nil
}
